import { currentLocale } from "./index";
const en = {
  objects: "Level objects", records: "Development records", connect: "Connect game directory", root: "VESPERIX project directory",
  connectionHelp: "Read level configuration from this local project. Source files stay in the repository.", refresh: "Refresh sources", loading: "Reading configuration…",
  noProject: "Choose a project first.", noZones: "No Zone configurations found.", zone: "Zone", allZones: "Include zones without routes", wholeZone: "Whole Zone",
  configuration: "Configuration view", runtime: "Encounter candidates; current Run and player verification are not observed.", entry: "Entry", gate: "Gate", shop: "Shop", location: "Location",
  missing: "Missing configuration", candidates: "Encounter candidates", noCandidates: "No content candidates are declared here.", first: "First entry", weight: "Base weight", associated: "Associated data", enemies: "Enemy templates",
  source: "Source files", viewSource: "View JSON", openSource: "Open source file", copyPath: "Copy path", copied: "Copied", close: "Close source", issues: "Configuration checks",
  modify: "Modify this object", verify: "Verify this object", request: "Object request", prompt: "What should the Agent do?", target: "Receiving task", chooseTarget: "Choose a task explicitly",
  noTargets: "No task is bound to this project directory. You can copy the context into a project task.", send: "Send request", copyContext: "Copy object context", cancel: "Cancel", submitted: "Request saved for delivery; execution is not yet verified.", sending: "Saving request…",
  results: "Related work and results", noResults: "No recorded work is linked to this object yet.", stale: "Sources changed since this record", unknownVersion: "Source version not checked", versionMatches: "Recorded source versions match", notExecuted: "No execution result recorded", openRecord: "Open record",
  verifyPrompt: "Verify this object's configuration references and a minimal real player path. Report actual results, remaining gaps, and the next step.", sourceChanged: "Refresh before sending if the configuration changed.", readonly: "This view reads source configuration; requests go to the selected task.", error: "Could not load", savedDraft: "Request draft kept locally.", neighbors: "Adjacent locations", noNeighbors: "No declared neighbors", resultHint: "Record status alone is not proof of runtime verification.", selected: "Selected", graphHelp: "Select a location to inspect its encounters and source files.", scope: "Selected object", pending: "Pending", failed: "Delivery failed", unknown: "Delivery status uncertain", received: "Received", handled: "Handled",
} as const;
type Key=keyof typeof en;
const zh:Record<Key,string>={
  objects:"关卡对象",records:"开发记录",connect:"连接游戏目录",root:"VESPERIX 项目目录",connectionHelp:"从这个本地项目读取关卡配置，源文件继续保存在原仓库中。",refresh:"刷新来源",loading:"正在读取配置…",
  noProject:"先选择一个项目。",noZones:"没有找到 Zone 配置。",zone:"区域",allZones:"包含未配置路线的区域",wholeZone:"整个区域",configuration:"配置视图",runtime:"这里展示遭遇候选；未读取本 Run 或玩家验证结果。",entry:"入口",gate:"关卡出口",shop:"商店",location:"地点",
  missing:"缺少配置",candidates:"遭遇候选",noCandidates:"这里没有声明内容候选。",first:"首次进入",weight:"基础权重",associated:"关联数据",enemies:"敌人模板",source:"来源文件",viewSource:"查看 JSON",openSource:"打开源文件",copyPath:"复制路径",copied:"已复制",close:"关闭来源",issues:"配置检查",
  modify:"修改这个对象",verify:"验证这个对象",request:"对象请求",prompt:"希望 Agent 做什么？",target:"接收任务",chooseTarget:"明确选择一个任务",noTargets:"当前没有关联到这个游戏目录的任务。可以复制上下文到项目任务中。",send:"发送请求",copyContext:"复制对象上下文",cancel:"取消",submitted:"请求已保存并进入投递流程，尚不代表执行或验证完成。",sending:"正在保存请求…",
  results:"相关工作与结果",noResults:"这个对象还没有关联的工作记录。",stale:"记录之后，配置已变化",unknownVersion:"来源版本未核对",versionMatches:"记录中的来源版本一致",notExecuted:"尚未记录执行结果",openRecord:"打开记录",verifyPrompt:"核对这个对象的配置引用和一条最小真实玩家路径，报告实际结果、未验证部分与下一步。",sourceChanged:"配置有变化时，先刷新再发送。",readonly:"这里读取源配置；请求将交给明确选择的任务。",error:"读取失败",savedDraft:"请求草稿保存在本地。",neighbors:"相邻地点",noNeighbors:"没有声明相邻地点",resultHint:"记录状态本身不代表运行时验证通过。",selected:"已选中",graphHelp:"选择地点，查看它的遭遇和来源文件。",scope:"当前对象",pending:"待投递",failed:"投递失败",unknown:"投递状态不确定",received:"已读取",handled:"已处理",
};
const ja:Record<Key,string>={...en,objects:"レベルオブジェクト",records:"開発記録",connect:"ゲームディレクトリを接続",root:"VESPERIX プロジェクト",refresh:"ソースを更新",loading:"設定を読み込み中…",zone:"ゾーン",wholeZone:"ゾーン全体",configuration:"設定ビュー",runtime:"遭遇候補の表示です。現在の Run とプレイヤー検証は未確認です。",entry:"入口",gate:"出口",shop:"ショップ",location:"場所",candidates:"遭遇候補",source:"ソースファイル",viewSource:"JSON を表示",openSource:"ソースを開く",copyPath:"パスをコピー",copied:"コピーしました",close:"閉じる",issues:"設定チェック",modify:"この対象を変更",verify:"この対象を検証",prompt:"Agent への依頼",target:"受信タスク",send:"依頼を送信",copyContext:"コンテキストをコピー",cancel:"キャンセル",results:"関連する作業と結果",openRecord:"記録を開く"};
export function gt(key:Key):string { const locale=currentLocale() as string;return locale==="zh-CN"?zh[key]:locale==="ja"?ja[key]:en[key]; }
