import { projectOwnerGet,projectOwnerPost,type WorkRecord } from "./project-record-api";
export type GameConnection={project_id:string;adapter:string;root:string;revision:number;connected_at_ms:number};
export type GameSource={path:string;hash:string;json:unknown};
export type GameZoneSummary={id:string;name:string;locations:number;routes:number;path:string};
export type GameCandidate={id:string;name:string;kind:string;description:string;weight:number|null;first_entry:boolean;gate:boolean;missing:boolean;associated_id:string|null;associated_name:string|null;enemies:string[];enemy_ids?:string[];loot_table_id?:string|null;loot_table_name?:string|null;paths:string[]};
export type GameLootPoint={id:string;name:string;kind:string;loot_table_id:string;loot_table_name:string|null;category:string|null;unlock_condition:string|null;missing:boolean;path:string|null};
export type GameLocation={id:string;name:string;description:string;x:number;y:number;role:string;missing:boolean;path:string|null;unlocks_zone:string|null;candidates:GameCandidate[];loot_points?:GameLootPoint[];rest?:boolean;unlock_cost?:unknown};
export type GameZoneView={zone:GameZoneSummary;dungeon_id?:string;description:string;entry:string;locations:GameLocation[];routes:Array<{from:string;to:string}>;sources:GameSource[];issues:Array<{severity:string;message:string;path:string}>;source_revision:string;runtime_verified:false};
export type GameTarget={source_id:string;thread_id:string;cwd:string;label:string};
export type GameResponse={connection:GameConnection;view:GameZoneView;records:WorkRecord[];targets:GameTarget[];zone_object_id:string;object_ids:Array<{location_id:string;object_id:string}>};
export type GameWorkspaceResponse=(GameResponse|{connection:GameConnection;view:null})&{zones:GameZoneSummary[];selected_zone_id?:string|null;view_error?:string|null};
export type GameAction={request_id:string;zone_id:string;location_id:string|null;expected_source_revision:string;intent:"modify"|"verify";prompt:string;source_id:string;target_thread_id:string};
export type GameActionResult={record_id:string;object_id:string;event:{seq:number};delivery?:{phase:string;error?:string|null}};
const base=(id:string)=>`/api/projects/${encodeURIComponent(id)}/game`;
export const fetchGameConnection=(id:string)=>projectOwnerGet<{connection:GameConnection|null}>(`${base(id)}/connection`);
export const connectGame=(id:string,root:string,revision:number,requestId:string)=>projectOwnerPost<GameConnection>(`${base(id)}/connection`,{root,expected_revision:revision,request_id:requestId});
export const fetchGameZones=(id:string)=>projectOwnerGet<{connection:GameConnection;zones:GameZoneSummary[]}>(`${base(id)}/zones`);
export const fetchGameZone=(id:string,zone:string)=>projectOwnerGet<GameResponse>(`${base(id)}/zones/${encodeURIComponent(zone)}`);
export const fetchGameView=(id:string,zone:string,refresh=false)=>projectOwnerGet<GameWorkspaceResponse>(`${base(id)}/view?${new URLSearchParams({...zone?{zone_id:zone}:{},...refresh?{refresh:"true"}:{}})}`);
export const fetchGameSource=(id:string,path:string)=>projectOwnerGet<GameSource>(`${base(id)}/source?${new URLSearchParams({path})}`);
export const submitGameAction=(id:string,request:GameAction)=>projectOwnerPost<GameActionResult>(`${base(id)}/actions`,request);
